### ISSUE TITLE
7#COULD Als User möchte ich die Möglichkeiten Mehrspieler Modus, um mit meinen Freunden spielen zu können.

### ISSUE THREAD

**Issue by rrecon** [ibwgr/Semesterarbeit_TuorHutterIlic#10]
- Multiplayer modus (CLient/Server)
- IPWindow, Combobox

**Comment by ladral** [comment]
Habe den Multiplayer Modus nun noch optimiert. Jetzt muss nicht mehr angegeben werden, welcher Spieler beginnt, sondern es wird automatisch im Programm ermittelt, welcher Spieler zuerst am Zug ist
